### ISSUE TITLE
node18 should be node20

### ISSUE THREAD

**Issue by hongbo-miao** [AkhileshNS/heroku-deploy#173]
After upgrading to v3.13.14,

I got [error](https://github.com/hongbo-miao/hongbomiao.com/actions/runs/7394234676/job/20115300945):

```sh
Download action repository 'actions/checkout@v4' (SHA:b4ffde65f46336ab88eb53be808477a3936bae11)
Download action repository 'actions/setup-node@v4' (SHA:b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8)
Download action repository 'akhileshns/heroku-deploy@v3.13.14' (SHA:74c2affebaa8010fb38a7ff9bb4568d57fd4fdf2)
Error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node18' is not supported, use 'docker', 'node12', 'node16' or 'node20' instead.')
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Fail to load akhileshns/heroku-deploy/v3.13.14/action.yml
```

I think `node18` should be `node20`. 🥲

**Comment by AkhileshNS** [comment]
Updated to version node20 in the latest version (`v3.13.15`), apologies for the slip up
